# Use postgres/example user/password credentials
version: '3.1'

services:
  postgres:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080